from random import randrange

gen_num = randrange(1,100)
chances = 1
print("-"*55)
print("\tNumber Guessing Game | Python Project...")
print("-"*55)
print("[+] You have Only 9 Chances to Guess the Numer which is generated by the System...")
print("[+] Number Guessing Game is started Here....")
print("[+] System genrated number is in range from 1 to 100...")

while chances <=9:
    print(f"\nYour {chances} Chance.")
    inp = int(input("Enter Your Guess Number :- "))
    if inp == gen_num:
        print("*"*80)
        print("-"*80)
        print("*"*80)
        print("\t[*] Your are Winnner. Your guess and System Generated number are equal.\t")
        print(f"\t\t[*] {inp}=={gen_num}\t\t")
        print("*"*80)
        print("-"*80)
        print("*"*80)
        break

    if gen_num > inp:
        print("[+] Your Guess is Low as Compare to Generated Number.")
        print("[+] Try Again, Better luck next time......")

    if gen_num < inp:
        print("[+] Your Guess is High as Compare to Generated Number.")
        print("[+] Try Again, Better luck next time......")

    chances+=1